import { FormConfig } from '@/types/formTypes';

const corporateTheme = {
  primaryColor: '#1E40AF',
  secondaryColor: '#3B82F6',
  backgroundColor: '#F8FAFC',
  headerBackgroundColor: '#1E40AF',
  headerTextColor: '#FFFFFF',
  subtitleColor: '#CBD5E1',
  buttonBackgroundColor: '#1E40AF',
  buttonTextColor: '#FFFFFF',
  buttonBorderRadius: 8,
  inputBackgroundColor: '#FFFFFF',
  inputBorderColor: '#D1D5DB',
  inputTextColor: '#374151',
  inputBorderRadius: 8,
  errorColor: '#DC2626',
  successColor: '#059669',
  warningColor: '#D97706',
  infoColor: '#0284C7',
  spacing: {
    xs: 4,
    sm: 8,
    md: 16,
    lg: 24,
    xl: 32,
  },
};

const creativeTheme = {
  primaryColor: '#7C3AED',
  secondaryColor: '#A855F7',
  backgroundColor: '#FAFAFA',
  headerBackgroundColor: '#7C3AED',
  headerTextColor: '#FFFFFF',
  subtitleColor: '#E0E7FF',
  buttonBackgroundColor: '#7C3AED',
  buttonTextColor: '#FFFFFF',
  buttonBorderRadius: 20,
  inputBackgroundColor: '#FFFFFF',
  inputBorderColor: '#C4B5FD',
  inputTextColor: '#374151',
  inputBorderRadius: 16,
  errorColor: '#EF4444',
  successColor: '#10B981',
  warningColor: '#F59E0B',
  infoColor: '#3B82F6',
  spacing: {
    xs: 6,
    sm: 12,
    md: 20,
    lg: 28,
    xl: 36,
  },
};

const medicalTheme = {
  primaryColor: '#059669',
  secondaryColor: '#10B981',
  backgroundColor: '#F0FDF4',
  headerBackgroundColor: '#059669',
  headerTextColor: '#FFFFFF',
  subtitleColor: '#BBF7D0',
  buttonBackgroundColor: '#059669',
  buttonTextColor: '#FFFFFF',
  buttonBorderRadius: 6,
  inputBackgroundColor: '#FFFFFF',
  inputBorderColor: '#A7F3D0',
  inputTextColor: '#374151',
  inputBorderRadius: 6,
  errorColor: '#DC2626',
  successColor: '#059669',
  warningColor: '#D97706',
  infoColor: '#0284C7',
  spacing: {
    xs: 4,
    sm: 8,
    md: 16,
    lg: 24,
    xl: 32,
  },
};

const ecommerceTheme = {
  primaryColor: '#DC2626',
  secondaryColor: '#EF4444',
  backgroundColor: '#FFFBEB',
  headerBackgroundColor: '#DC2626',
  headerTextColor: '#FFFFFF',
  subtitleColor: '#FECACA',
  buttonBackgroundColor: '#DC2626',
  buttonTextColor: '#FFFFFF',
  buttonBorderRadius: 12,
  inputBackgroundColor: '#FFFFFF',
  inputBorderColor: '#FBBF24',
  inputTextColor: '#374151',
  inputBorderRadius: 12,
  errorColor: '#DC2626',
  successColor: '#059669',
  warningColor: '#D97706',
  infoColor: '#0284C7',
  spacing: {
    xs: 4,
    sm: 8,
    md: 16,
    lg: 24,
    xl: 32,
  },
};

const formConfigs: { [key: string]: FormConfig } = {
  corporate: {
    id: 'corporate',
    title: 'Corporate Registration',
    subtitle: 'Professional business registration form',
    type: 'simple',
    theme: corporateTheme,
    endpoint: '/api/corporate/register',
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      'X-API-Key': 'corporate-api-key',
    },
    banners: [
      {
        id: 'info',
        type: 'info',
        title: 'Important Notice',
        message: 'All fields marked with * are required for processing your application.',
        dismissible: true,
        style: {
          backgroundColor: '#EBF8FF',
          borderColor: '#0284C7',
          borderWidth: 1,
          borderRadius: 8,
          padding: 16,
          margin: 16,
          textColor: '#0C4A6E',
          titleColor: '#0284C7',
        },
      },
    ],
    groups: [
      {
        id: 'basic-info',
        title: 'Basic Information',
        subtitle: 'Please provide your basic details',
        fields: [
          {
            id: 'firstName',
            type: 'text',
            label: 'First Name',
            placeholder: 'Enter your first name',
            required: true,
            validation: [
              { type: 'required', message: 'First name is required' },
              { type: 'min', value: 2, message: 'First name must be at least 2 characters' },
            ],
          },
          {
            id: 'lastName',
            type: 'text',
            label: 'Last Name',
            placeholder: 'Enter your last name',
            required: true,
            validation: [
              { type: 'required', message: 'Last name is required' },
              { type: 'min', value: 2, message: 'Last name must be at least 2 characters' },
            ],
          },
          {
            id: 'email',
            type: 'email',
            label: 'Email Address',
            placeholder: 'Enter your email',
            required: true,
            validation: [
              { type: 'required', message: 'Email is required' },
              { type: 'email', message: 'Please enter a valid email address' },
            ],
          },
          {
            id: 'phone',
            type: 'phone',
            label: 'Phone Number',
            placeholder: 'Enter your phone number',
            required: true,
            validation: [
              { type: 'required', message: 'Phone number is required' },
              { type: 'pattern', value: /^\+?[\d\s-()]+$/, message: 'Please enter a valid phone number' },
            ],
          },
        ],
        style: {
          backgroundColor: '#FFFFFF',
          borderColor: '#E5E7EB',
          borderWidth: 1,
          borderRadius: 8,
          padding: 16,
          margin: 16,
          titleColor: '#1F2937',
          titleFontSize: 18,
          titleFontWeight: '600',
        },
      },
      {
        id: 'company-info',
        title: 'Company Information',
        subtitle: 'Details about your company',
        fields: [
          {
            id: 'companyName',
            type: 'text',
            label: 'Company Name',
            placeholder: 'Enter company name',
            required: true,
            validation: [
              { type: 'required', message: 'Company name is required' },
            ],
          },
          {
            id: 'industry',
            type: 'select',
            label: 'Industry',
            placeholder: 'Select industry',
            required: true,
            options: [
              { value: 'technology', label: 'Technology' },
              { value: 'healthcare', label: 'Healthcare' },
              { value: 'finance', label: 'Finance' },
              { value: 'retail', label: 'Retail' },
              { value: 'manufacturing', label: 'Manufacturing' },
              { value: 'other', label: 'Other' },
            ],
            validation: [
              { type: 'required', message: 'Industry selection is required' },
            ],
          },
          {
            id: 'companySize',
            type: 'radio',
            label: 'Company Size',
            required: true,
            options: [
              { value: '1-10', label: '1-10 employees' },
              { value: '11-50', label: '11-50 employees' },
              { value: '51-200', label: '51-200 employees' },
              { value: '200+', label: '200+ employees' },
            ],
            validation: [
              { type: 'required', message: 'Company size is required' },
            ],
          },
        ],
        style: {
          backgroundColor: '#FFFFFF',
          borderColor: '#E5E7EB',
          borderWidth: 1,
          borderRadius: 8,
          padding: 16,
          margin: 16,
          titleColor: '#1F2937',
          titleFontSize: 18,
          titleFontWeight: '600',
        },
      },
    ],
    submitButtonText: 'Submit Application',
    resetButtonText: 'Reset Form',
    showResetButton: true,
    callbacks: {
      onSubmit: 'handleCorporateSubmit',
      onChange: 'handleCorporateChange',
    },
  },

  creative: {
    id: 'creative',
    title: 'Creative Profile',
    subtitle: 'Showcase your creative talents',
    type: 'simple',
    theme: creativeTheme,
    endpoint: '/api/creative/profile',
    method: 'POST',
    banners: [
      {
        id: 'welcome',
        type: 'success',
        title: 'Welcome Creative!',
        message: 'Let your creativity shine through this personalized form.',
        dismissible: true,
        style: {
          backgroundColor: '#F0FDF4',
          borderColor: '#10B981',
          borderWidth: 2,
          borderRadius: 16,
          padding: 20,
          margin: 20,
          textColor: '#065F46',
          titleColor: '#10B981',
        },
      },
    ],
    groups: [
      {
        id: 'personal',
        title: 'Personal Touch',
        subtitle: 'Tell us about yourself',
        fields: [
          {
            id: 'artistName',
            type: 'text',
            label: 'Artist Name',
            placeholder: 'Your creative alias',
            required: true,
            style: {
              backgroundColor: '#FFFFFF',
              borderColor: '#C4B5FD',
              borderWidth: 2,
              borderRadius: 16,
              padding: 16,
              fontSize: 16,
              color: '#374151',
            },
          },
          {
            id: 'bio',
            type: 'textarea',
            label: 'Creative Bio',
            placeholder: 'Tell us your creative story...',
            required: true,
            style: {
              backgroundColor: '#FFFFFF',
              borderColor: '#C4B5FD',
              borderWidth: 2,
              borderRadius: 16,
              padding: 16,
              fontSize: 16,
              color: '#374151',
              height: 120,
            },
          },
        ],
        style: {
          backgroundColor: '#FFFFFF',
          borderColor: '#C4B5FD',
          borderWidth: 2,
          borderRadius: 20,
          padding: 20,
          margin: 20,
          titleColor: '#7C3AED',
          titleFontSize: 20,
          titleFontWeight: 'bold',
        },
      },
      {
        id: 'skills',
        title: 'Creative Skills',
        subtitle: 'What makes you unique?',
        fields: [
          {
            id: 'primarySkill',
            type: 'select',
            label: 'Primary Skill',
            placeholder: 'Choose your main talent',
            required: true,
            options: [
              { value: 'design', label: 'Graphic Design' },
              { value: 'photography', label: 'Photography' },
              { value: 'writing', label: 'Creative Writing' },
              { value: 'music', label: 'Music Production' },
              { value: 'video', label: 'Video Editing' },
              { value: 'illustration', label: 'Illustration' },
            ],
            style: {
              backgroundColor: '#FFFFFF',
              borderColor: '#C4B5FD',
              borderWidth: 2,
              borderRadius: 16,
              padding: 16,
              fontSize: 16,
              color: '#374151',
            },
          },
          {
            id: 'secondarySkills',
            type: 'multiselect',
            label: 'Secondary Skills',
            placeholder: 'Select additional skills',
            options: [
              { value: 'ui-ux', label: 'UI/UX Design' },
              { value: 'branding', label: 'Branding' },
              { value: 'animation', label: 'Animation' },
              { value: 'web-design', label: 'Web Design' },
              { value: 'social-media', label: 'Social Media' },
              { value: 'copywriting', label: 'Copywriting' },
            ],
            style: {
              backgroundColor: '#FFFFFF',
              borderColor: '#C4B5FD',
              borderWidth: 2,
              borderRadius: 16,
              padding: 16,
              fontSize: 16,
              color: '#374151',
            },
          },
        ],
        style: {
          backgroundColor: '#FFFFFF',
          borderColor: '#C4B5FD',
          borderWidth: 2,
          borderRadius: 20,
          padding: 20,
          margin: 20,
          titleColor: '#7C3AED',
          titleFontSize: 20,
          titleFontWeight: 'bold',
        },
      },
    ],
    submitButtonText: 'Create Profile',
    resetButtonText: 'Start Over',
    showResetButton: true,
  },

  medical: {
    id: 'medical',
    title: 'Patient Registration',
    subtitle: 'Healthcare information wizard',
    type: 'wizard',
    theme: medicalTheme,
    endpoint: '/api/medical/patient',
    method: 'POST',
    banners: [
      {
        id: 'privacy',
        type: 'info',
        title: 'Privacy Notice',
        message: 'Your medical information is protected under HIPAA regulations.',
        dismissible: false,
        style: {
          backgroundColor: '#ECFDF5',
          borderColor: '#059669',
          borderWidth: 1,
          borderRadius: 6,
          padding: 16,
          margin: 16,
          textColor: '#064E3B',
          titleColor: '#059669',
        },
      },
    ],
    steps: [
      {
        id: 'personal-info',
        title: 'Personal Information',
        subtitle: 'Basic patient details',
        groups: [
          {
            id: 'personal',
            title: 'Personal Details',
            fields: [
              {
                id: 'fullName',
                type: 'text',
                label: 'Full Name',
                placeholder: 'Enter full name',
                required: true,
                validation: [
                  { type: 'required', message: 'Full name is required' },
                ],
              },
              {
                id: 'dateOfBirth',
                type: 'date',
                label: 'Date of Birth',
                required: true,
                validation: [
                  { type: 'required', message: 'Date of birth is required' },
                ],
              },
              {
                id: 'gender',
                type: 'radio',
                label: 'Gender',
                required: true,
                options: [
                  { value: 'male', label: 'Male' },
                  { value: 'female', label: 'Female' },
                  { value: 'other', label: 'Other' },
                  { value: 'prefer-not-to-say', label: 'Prefer not to say' },
                ],
                validation: [
                  { type: 'required', message: 'Gender selection is required' },
                ],
              },
            ],
            style: {
              backgroundColor: '#FFFFFF',
              borderColor: '#A7F3D0',
              borderWidth: 1,
              borderRadius: 6,
              padding: 16,
              margin: 16,
              titleColor: '#064E3B',
              titleFontSize: 18,
              titleFontWeight: '600',
            },
          },
        ],
        nextButtonText: 'Next: Contact Info',
      },
      {
        id: 'contact-info',
        title: 'Contact Information',
        subtitle: 'How can we reach you?',
        groups: [
          {
            id: 'contact',
            title: 'Contact Details',
            fields: [
              {
                id: 'email',
                type: 'email',
                label: 'Email Address',
                placeholder: 'Enter email address',
                required: true,
                validation: [
                  { type: 'required', message: 'Email is required' },
                  { type: 'email', message: 'Please enter a valid email' },
                ],
              },
              {
                id: 'phone',
                type: 'phone',
                label: 'Phone Number',
                placeholder: 'Enter phone number',
                required: true,
                validation: [
                  { type: 'required', message: 'Phone number is required' },
                ],
              },
              {
                id: 'emergencyContact',
                type: 'text',
                label: 'Emergency Contact',
                placeholder: 'Name and phone number',
                required: true,
                validation: [
                  { type: 'required', message: 'Emergency contact is required' },
                ],
              },
            ],
            style: {
              backgroundColor: '#FFFFFF',
              borderColor: '#A7F3D0',
              borderWidth: 1,
              borderRadius: 6,
              padding: 16,
              margin: 16,
              titleColor: '#064E3B',
              titleFontSize: 18,
              titleFontWeight: '600',
            },
          },
        ],
        nextButtonText: 'Next: Medical History',
        previousButtonText: 'Back: Personal Info',
      },
      {
        id: 'medical-history',
        title: 'Medical History',
        subtitle: 'Please provide relevant medical information',
        groups: [
          {
            id: 'medical',
            title: 'Medical Information',
            fields: [
              {
                id: 'allergies',
                type: 'textarea',
                label: 'Allergies',
                placeholder: 'List any allergies or write "None"',
                required: true,
                validation: [
                  { type: 'required', message: 'Please specify allergies or enter "None"' },
                ],
                style: {
                  height: 80,
                },
              },
              {
                id: 'medications',
                type: 'textarea',
                label: 'Current Medications',
                placeholder: 'List current medications or write "None"',
                required: true,
                validation: [
                  { type: 'required', message: 'Please specify medications or enter "None"' },
                ],
                style: {
                  height: 80,
                },
              },
              {
                id: 'conditions',
                type: 'multiselect',
                label: 'Medical Conditions',
                placeholder: 'Select applicable conditions',
                options: [
                  { value: 'diabetes', label: 'Diabetes' },
                  { value: 'hypertension', label: 'Hypertension' },
                  { value: 'heart-disease', label: 'Heart Disease' },
                  { value: 'asthma', label: 'Asthma' },
                  { value: 'arthritis', label: 'Arthritis' },
                  { value: 'depression', label: 'Depression' },
                  { value: 'anxiety', label: 'Anxiety' },
                  { value: 'none', label: 'None of the above' },
                ],
              },
            ],
            style: {
              backgroundColor: '#FFFFFF',
              borderColor: '#A7F3D0',
              borderWidth: 1,
              borderRadius: 6,
              padding: 16,
              margin: 16,
              titleColor: '#064E3B',
              titleFontSize: 18,
              titleFontWeight: '600',
            },
          },
        ],
        nextButtonText: 'Complete Registration',
        previousButtonText: 'Back: Contact Info',
      },
    ],
    submitButtonText: 'Complete Registration',
    callbacks: {
      onSubmit: 'handleMedicalSubmit',
    },
  },

  ecommerce: {
    id: 'ecommerce',
    title: 'Checkout Form',
    subtitle: 'Complete your purchase',
    type: 'simple',
    theme: ecommerceTheme,
    endpoint: '/api/ecommerce/checkout',
    method: 'POST',
    banners: [
      {
        id: 'shipping',
        type: 'warning',
        title: 'Free Shipping',
        message: 'Orders over $50 qualify for free shipping!',
        dismissible: true,
        style: {
          backgroundColor: '#FFFBEB',
          borderColor: '#F59E0B',
          borderWidth: 2,
          borderRadius: 12,
          padding: 18,
          margin: 18,
          textColor: '#92400E',
          titleColor: '#D97706',
        },
      },
    ],
    groups: [
      {
        id: 'billing',
        title: 'Billing Information',
        subtitle: 'Enter your billing details',
        fields: [
          {
            id: 'fullName',
            type: 'text',
            label: 'Full Name',
            placeholder: 'Enter full name',
            required: true,
            validation: [
              { type: 'required', message: 'Full name is required' },
            ],
            style: {
              backgroundColor: '#FFFFFF',
              borderColor: '#FBBF24',
              borderWidth: 2,
              borderRadius: 12,
              padding: 16,
              fontSize: 16,
              color: '#374151',
            },
          },
          {
            id: 'email',
            type: 'email',
            label: 'Email Address',
            placeholder: 'Enter email for receipt',
            required: true,
            validation: [
              { type: 'required', message: 'Email is required' },
              { type: 'email', message: 'Please enter a valid email' },
            ],
            style: {
              backgroundColor: '#FFFFFF',
              borderColor: '#FBBF24',
              borderWidth: 2,
              borderRadius: 12,
              padding: 16,
              fontSize: 16,
              color: '#374151',
            },
          },
          {
            id: 'address',
            type: 'text',
            label: 'Street Address',
            placeholder: 'Enter street address',
            required: true,
            validation: [
              { type: 'required', message: 'Street address is required' },
            ],
            style: {
              backgroundColor: '#FFFFFF',
              borderColor: '#FBBF24',
              borderWidth: 2,
              borderRadius: 12,
              padding: 16,
              fontSize: 16,
              color: '#374151',
            },
          },
          {
            id: 'city',
            type: 'text',
            label: 'City',
            placeholder: 'Enter city',
            required: true,
            validation: [
              { type: 'required', message: 'City is required' },
            ],
            style: {
              backgroundColor: '#FFFFFF',
              borderColor: '#FBBF24',
              borderWidth: 2,
              borderRadius: 12,
              padding: 16,
              fontSize: 16,
              color: '#374151',
            },
          },
          {
            id: 'zipCode',
            type: 'text',
            label: 'ZIP Code',
            placeholder: 'Enter ZIP code',
            required: true,
            validation: [
              { type: 'required', message: 'ZIP code is required' },
              { type: 'pattern', value: /^\d{5}(-\d{4})?$/, message: 'Please enter a valid ZIP code' },
            ],
            style: {
              backgroundColor: '#FFFFFF',
              borderColor: '#FBBF24',
              borderWidth: 2,
              borderRadius: 12,
              padding: 16,
              fontSize: 16,
              color: '#374151',
            },
          },
        ],
        style: {
          backgroundColor: '#FFFFFF',
          borderColor: '#FBBF24',
          borderWidth: 2,
          borderRadius: 12,
          padding: 18,
          margin: 18,
          titleColor: '#DC2626',
          titleFontSize: 20,
          titleFontWeight: 'bold',
        },
      },
      {
        id: 'payment',
        title: 'Payment Method',
        subtitle: 'Choose your payment option',
        fields: [
          {
            id: 'paymentMethod',
            type: 'radio',
            label: 'Payment Method',
            required: true,
            options: [
              { value: 'credit-card', label: 'Credit Card' },
              { value: 'paypal', label: 'PayPal' },
              { value: 'apple-pay', label: 'Apple Pay' },
              { value: 'google-pay', label: 'Google Pay' },
            ],
            validation: [
              { type: 'required', message: 'Payment method is required' },
            ],
          },
          {
            id: 'savePayment',
            type: 'checkbox',
            label: 'Save payment method for future purchases',
            defaultValue: false,
          },
          {
            id: 'agreeToTerms',
            type: 'checkbox',
            label: 'I agree to the Terms of Service and Privacy Policy',
            required: true,
            validation: [
              { type: 'required', message: 'You must agree to the terms' },
            ],
          },
        ],
        style: {
          backgroundColor: '#FFFFFF',
          borderColor: '#FBBF24',
          borderWidth: 2,
          borderRadius: 12,
          padding: 18,
          margin: 18,
          titleColor: '#DC2626',
          titleFontSize: 20,
          titleFontWeight: 'bold',
        },
      },
    ],
    submitButtonText: 'Complete Purchase',
    resetButtonText: 'Clear Form',
    showResetButton: true,
    callbacks: {
      onSubmit: 'handleEcommerceSubmit',
    },
  },
};

export const getFormConfig = (testCase: string): FormConfig => {
  return formConfigs[testCase] || formConfigs.corporate;
};